[package]
name = "platform-macos"
version = "0.1.0"
edition = "2021"

[dependencies]
core-foundation = "0.9"
core-graphics = "0.23"
objc2 = "0.5"
objc2-app-kit = "0.2"
objc2-foundation = "0.2"
plist = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
